name: Build
run-name: Build application
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install g++ g++-mingw-w64
      - run: make build
      - run: make build-windows
